version: '3.3'

services:
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: hockey-stick
    ports:
      - 8081:80
    volumes:
      - ./haproxy.cfg:/etc/haproxy/haproxy.cfg
    depends_on:
      - http-echo

  http-echo:
    image: mendhak/http-https-echo
    environment:
      - DISABLE_REQUEST_LOGS=true
      - HTTP_PORT=5678
