version: '3.8'

services:
  haproxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: hockey-stick
    ports:
      - 80:80
    volumes:
      - ./haproxy.cfg:/etc/haproxy/haproxy.cfg

  http-echo:
    image: mendhak/http-https-echo
    depends_on:
      - haproxy
    environment:
      - DISABLE_REQUEST_LOGS=true
      - HTTP_PORT=5678
